### ISSUE TITLE
Missing setup commands to the guide for setting up the runner

### ISSUE THREAD

**Issue by erictaur** [antmicro/runner#3]
**Describe the enhancement**
The issue provides a small list of missing commands that help set up the runner.

### `Install.sh` cannot be run out of the box
Encountered error: 
```
missing <priority> for update-alternatives 
```
Currently applied fixes that sort of fixed the issue: 
Appended a 1 at the end of `update-alternatives --install /usr/bin/python python /usr/bin/python3`

---

### Missing commands when sshing into the coordinator instance 

wget is not installed:
(For `wget`ting the installation script)
```
sudo apt install wget
```

After downloading the install script has to be made executable
(Something not as strong as 777 though)
```
chmod 777 ./install.sh
```

**Code Snippet**
N/A

**Additional information**
N/A

FYI @msaligane

**Comment by AdamOlech** [comment]
Hey @erictaur, thanks for reporting the issue.

I fixed the installation script by adding the missing priority argument. Additionally, I added the command to install wget prior to downloading the aforementioned scripted (I tend to make an assertion that it is installed by default, but it turns out it's not 😄).

The `chmod` command is not necessary. Instead, one has to [redirect wget's output to standard output](https://github.com/antmicro/runner/commit/145a240a5708f55309b993621efc938f4c751944) -- then it works as intended (of course common sense has it that you should inspect the script before doing that).
